const statesInfo = [
  {
    backgroundImage: ".././assets/al-bg.jpg",
    name: "Alabama",
    stateCapital: "Montgomery",
    wrongOptionOne: "Tuscaloosa",
    wrongOptionTwo: "Mobile",
    wrongOptionThree: "Huntsville",
  },
  {
    backgroundImage: ".././assets/ak-bg.jpg",
    name: "Alaska",
    stateCapital: "Juneau",
    wrongOptionOne: "Anchorage",
    wrongOptionTwo: "Barrow",
    wrongOptionThree: "Naknek",
  },
  {
    backgroundImage: ".././assets/az-bg.jpg",
    name: "Arizona",
    stateCapital: "Phoenix",
    wrongOptionOne: "Yuma",
    wrongOptionTwo: "Flagstaff",
    wrongOptionThree: "Scottsdale",
  },
  {
    backgroundImage: ".././assets/ar-bg.jpg",
    name: "Arkansas",
    stateCapital: "Little Rock",
    wrongOptionOne: "Springfield",
    wrongOptionTwo: "Eureka Springs",
    wrongOptionThree: "Fayetteville",
  },
  {
    backgroundImage: ".././assets/ca-bg.jpg",
    name: "California",
    stateCapital: "Sacramento",
    wrongOptionOne: "Los Angeles",
    wrongOptionTwo: "San Diego",
    wrongOptionThree: "Pacific Palisades",
  },
  {
    backgroundImage: ".././assets/co-bg.jpg",
    name: "Colorado",
    stateCapital: "Denver",
    wrongOptionOne: "Fort Collins",
    wrongOptionTwo: "Boulder",
    wrongOptionThree: "Loveland",
  },
  {
    backgroundImage: ".././assets/ct-bg.jpg",
    name: "Connecticut",
    stateCapital: "Hartford",
    wrongOptionOne: "Bridgeport",
    wrongOptionTwo: "Bristol",
    wrongOptionThree: "Norwalk",
  },
  {
    backgroundImage: ".././assets/de-bg.jpg",
    name: "Delaware",
    stateCapital: "Dover",
    wrongOptionOne: "Wilmington",
    wrongOptionTwo: "Smyrna",
    wrongOptionThree: "Seaford",
  },
  {
    backgroundImage: ".././assets/fl-bg.jpg",
    name: "Florida",
    stateCapital: "Tallahassee",
    wrongOptionOne: "Jacksonville",
    wrongOptionTwo: "Miami",
    wrongOptionThree: "Gainesville",
  },
  {
    backgroundImage: ".././assets/ga-bg.jpg",
    name: "Georgia",
    stateCapital: "Atlanta",
    wrongOptionOne: "Savannah",
    wrongOptionTwo: "Athens",
    wrongOptionThree: "Augusta",
  },
  {
    backgroundImage: ".././assets/hi-bg.jpg",
    name: "Hawaii",
    stateCapital: "Honolulu",
    wrongOptionOne: "Pearl Harbor",
    wrongOptionTwo: "Waipahu",
    wrongOptionThree: "Kailua",
  },
  {
    backgroundImage: ".././assets/id-bg.jpg",
    name: "Idaho",
    stateCapital: "Boise",
    wrongOptionOne: "Twin Falls",
    wrongOptionTwo: "Caldwell",
    wrongOptionThree: "Nampa",
  },
  {
    backgroundImage: ".././assets/il-bg.jpg",
    name: "Illinois",
    stateCapital: "Springfield",
    wrongOptionOne: "Chicago",
    wrongOptionTwo: "Joliet",
    wrongOptionThree: "Aurora",
  },
  {
    backgroundImage: ".././assets/in-bg.jpg",
    name: "Indiana",
    stateCapital: "Indianapolis",
    wrongOptionOne: "Shipshewana",
    wrongOptionTwo: "South Bend",
    wrongOptionThree: "Gary",
  },
  {
    backgroundImage: ".././assets/ia-bg.jpg",
    name: "Iowa",
    stateCapital: "Des Moines",
    wrongOptionOne: "Iowa City",
    wrongOptionTwo: "Council Bluffs",
    wrongOptionThree: "Cedar Rapids",
  },
  {
    backgroundImage: ".././assets/ks-bg.jpg",
    name: "Kansas",
    stateCapital: "Topeka",
    wrongOptionOne: "Wichita",
    wrongOptionTwo: "Kansas City",
    wrongOptionThree: "Lawrence",
  },
  {
    backgroundImage: ".././assets/ky-bg.jpg",
    name: "Kentucky",
    stateCapital: "Frankfort",
    wrongOptionOne: "Lexington",
    wrongOptionTwo: "Louisville",
    wrongOptionThree: "Bowling Green",
  },
  {
    backgroundImage: ".././assets/la-bg.jpg",
    name: "Louisiana",
    stateCapital: "Baton Rouge",
    wrongOptionOne: "Shreveport",
    wrongOptionTwo: "New Orleans",
    wrongOptionThree: "Monroe",
  },
  {
    backgroundImage: ".././assets/me-bg.jpg",
    name: "Maine",
    stateCapital: "Augusta",
    wrongOptionOne: "Portland",
    wrongOptionTwo: "Berwick",
    wrongOptionThree: "Andover",
  },
  {
    backgroundImage: ".././assets/md-bg.jpg",
    name: "Maryland",
    stateCapital: "Annapolis",
    wrongOptionOne: "Baltimore",
    wrongOptionTwo: "Frederick",
    wrongOptionThree: "Bethesda",
  },
  {
    backgroundImage: ".././assets/ma-bg.jpg",
    name: "Massachusetts",
    stateCapital: "Boston",
    wrongOptionOne: "Cambridge",
    wrongOptionTwo: "Bedford",
    wrongOptionThree: "Worcester",
  },
  {
    backgroundImage: ".././assets/mi-bg.jpg",
    name: "Michigan",
    stateCapital: "Lansing",
    wrongOptionOne: "Grand Rapids",
    wrongOptionTwo: "Detroit",
    wrongOptionThree: "Traverse City",
  },
  {
    backgroundImage: ".././assets/mn-bg.jpg",
    name: "Minnesota",
    stateCapital: "St. Paul",
    wrongOptionOne: "Minneapolis",
    wrongOptionTwo: "Duluth",
    wrongOptionThree: "Rochester",
  },
  {
    backgroundImage: ".././assets/ms-bg.jpg",
    name: "Mississippi",
    stateCapital: "Jackson",
    wrongOptionOne: "Biloxi",
    wrongOptionTwo: "Hattiesburg",
    wrongOptionThree: "Tupelo",
  },
  {
    backgroundImage: ".././assets/mo-bg.jpg",
    name: "Missouri",
    stateCapital: "Jefferson City",
    wrongOptionOne: "Springfield",
    wrongOptionTwo: "Kansas City",
    wrongOptionThree: "Hannibal",
  },
  {
    backgroundImage: ".././assets/mt-bg.jpg",
    name: "Montana",
    stateCapital: "Helena",
    wrongOptionOne: "Big Sky",
    wrongOptionTwo: "Billings",
    wrongOptionThree: "Bozeman",
  },
  {
    backgroundImage: ".././assets/ne-bg.jpg",
    name: "Nebraska",
    stateCapital: "Lincoln",
    wrongOptionOne: "Omaha",
    wrongOptionTwo: "Bellevue",
    wrongOptionThree: "Papillion",
  },
  {
    backgroundImage: ".././assets/nv-bg.jpg",
    name: "Nevada",
    stateCapital: "Carson City",
    wrongOptionOne: "Reno",
    wrongOptionTwo: "Las Vegas",
    wrongOptionThree: "Sparks",
  },
  {
    backgroundImage: ".././assets/nh-bg.jpg",
    name: "New Hampshire",
    stateCapital: "Concord",
    wrongOptionOne: "Manchester",
    wrongOptionTwo: "Portsmouth",
    wrongOptionThree: "Derry",
  },
  {
    backgroundImage: ".././assets/nj-bg.jpg",
    name: "New Jersey",
    stateCapital: "Trenton",
    wrongOptionOne: "Newark",
    wrongOptionTwo: "Garden City",
    wrongOptionThree: "Rutherford",
  },
  {
    backgroundImage: ".././assets/nm-bg.jpg",
    name: "New Mexico",
    stateCapital: "Santa Fe",
    wrongOptionOne: "Albuquerque",
    wrongOptionTwo: "Las Cruces",
    wrongOptionThree: "Roswell",
  },
  {
    backgroundImage: ".././assets/ny-bg.jpg",
    name: "New York",
    stateCapital: "Albany",
    wrongOptionOne: "Manhattan",
    wrongOptionTwo: "Syracuse",
    wrongOptionThree: "Staten Island",
  },
  {
    backgroundImage: ".././assets/nc-bg.jpg",
    name: "North Carolina",
    stateCapital: "Raleigh",
    wrongOptionOne: "Charlotte",
    wrongOptionTwo: "Chapel Hill",
    wrongOptionThree: "Greensboro",
  },
  {
    backgroundImage: ".././assets/nd-bg.jpg",
    name: "North Dakota",
    stateCapital: "Bismarck",
    wrongOptionOne: "Fargo",
    wrongOptionTwo: "Mandan",
    wrongOptionThree: "Grand Forks",
  },
  {
    backgroundImage: ".././assets/oh-bg.jpg",
    name: "Ohio",
    stateCapital: "Columbus",
    wrongOptionOne: "Cincinnati",
    wrongOptionTwo: "Cleveland",
    wrongOptionThree: "Youngstown",
  },
  {
    backgroundImage: ".././assets/ok-bg.jpg",
    name: "Oklahoma",
    stateCapital: "Oklahoma City",
    wrongOptionOne: "Tulsa",
    wrongOptionTwo: "Broken Arrow",
    wrongOptionThree: "Comanche",
  },
  {
    backgroundImage: ".././assets/or-bg.jpg",
    name: "Oregon",
    stateCapital: "Salem",
    wrongOptionOne: "Portland",
    wrongOptionTwo: "Medford",
    wrongOptionThree: "McMinnville",
  },
  {
    backgroundImage: ".././assets/pa-bg.jpg",
    name: "Pennsylvania",
    stateCapital: "Harrisburg",
    wrongOptionOne: "Pittsburgh",
    wrongOptionTwo: "Scranton",
    wrongOptionThree: "Philadelphia",
  },
  {
    backgroundImage: ".././assets/ri-bg.jpg",
    name: "Rhode Island",
    stateCapital: "Providence",
    wrongOptionOne: "Warwick",
    wrongOptionTwo: "Pawtucket",
    wrongOptionThree: "Newport",
  },
  {
    backgroundImage: ".././assets/sc-bg.jpg",
    name: "South Carolina",
    stateCapital: "Columbia",
    wrongOptionOne: "Charleston",
    wrongOptionTwo: "Myrtle Beach",
    wrongOptionThree: "Greensboro",
  },
  {
    backgroundImage: ".././assets/sd-bg.jpg",
    name: "South Dakota",
    stateCapital: "Pierre",
    wrongOptionOne: "Brookings",
    wrongOptionTwo: "Sioux Falls",
    wrongOptionThree: "Big Stone City",
  },
  {
    backgroundImage: ".././assets/tn-bg.jpg",
    name: "Tennessee",
    stateCapital: "Nashville",
    wrongOptionOne: "Gatlinburg",
    wrongOptionTwo: "Memphis",
    wrongOptionThree: "Dollywood",
  },
  {
    backgroundImage: ".././assets/tx-bg.jpg",
    name: "Texas",
    stateCapital: "Austin",
    wrongOptionOne: "Houston",
    wrongOptionTwo: "San Antonio",
    wrongOptionThree: "Dallas",
  },
  {
    backgroundImage: ".././assets/ut-bg.jpg",
    name: "Utah",
    stateCapital: "Salt Lake City",
    wrongOptionOne: "Provo",
    wrongOptionTwo: "Ogden",
    wrongOptionThree: "South Jordan",
  },
  {
    backgroundImage: ".././assets/vt-bg.jpg",
    name: "Vermont",
    stateCapital: "Montpelier",
    wrongOptionOne: "Burlington",
    wrongOptionTwo: "Winooski",
    wrongOptionThree: "Concord",
  },
  {
    backgroundImage: ".././assets/va-bg.jpg",
    name: "Virginia",
    stateCapital: "Richmond",
    wrongOptionOne: "Virginia Beach",
    wrongOptionTwo: "Chesapeake",
    wrongOptionThree: "Alexandria",
  },
  {
    backgroundImage: ".././assets/wa-bg.jpg",
    name: "Washington",
    stateCapital: "Olympia",
    wrongOptionOne: "Seattle",
    wrongOptionTwo: "Tacoma",
    wrongOptionThree: "Linden",
  },
  {
    backgroundImage: ".././assets/wv-bg.jpg",
    name: "West Virginia",
    stateCapital: "Charleston",
    wrongOptionOne: "Morgantown",
    wrongOptionTwo: "Wheeling",
    wrongOptionThree: "Clarkston",
  },
  {
    backgroundImage: ".././assets/wi-bg.jpg",
    name: "Wisconsin",
    stateCapital: "Madison",
    wrongOptionOne: "Milwaukee",
    wrongOptionTwo: "Green Bay",
    wrongOptionThree: "Fond du Lac",
  },
  {
    backgroundImage: ".././assets/wy-bg.jpg",
    name: "Wyoming",
    stateCapital: "Cheyenne",
    wrongOptionOne: "Jackson Hole",
    wrongOptionTwo: "Casper",
    wrongOptionThree: "Sheridan",
  },
];

export default statesInfo;
